### ISSUE TITLE
issue with menu_manager : add all zenpage pages

### ISSUE THREAD

**Issue by vincent3569** [zenphoto/zenphoto#1227]
Hi

I have an issue when I try to add all pages (with add menu item "all zenpage page".
all pages are not added (all expect one: 16/17 pages are added) and I have this message in debud log:

````
WARNING: A non-numeric value encountered in /home/avbo7291/public_html/zenphoto__test/zp-core/zp-extensions/menu_manager/menu_manager-admin-functions.php on line 384
addPagesToDatabase called from addItem (menu_manager-admin-functions.php [480])
from menu_tab_edit.php [23] 
````

If I remove all these pages from my menu, the missing page appears and I don't have any other message in debug log.
In taht case, I can see this page in FE, and if I remove this page from my custom menu, I don't have any other message in debug log 

This page is called 'test' (titlelink 'test') and the only content is the contact macro `[CONTACTFORM]`.

**Comment by acrylian** [comment]
Will take a look if I can reproduce that. Have indeed to admit I almost never use these automatic function myself and always create manual menus.

**Comment by sbillard** [comment]
The most likely cause of this is the 'sort_order' field of this page in the database. Can you look and see what the value of that field is?

**Comment by vincent3569** [comment]
in zp_pages, indeed, sort order is empty for this page (even if this is my firt page) and for Porfolio page (the following one), its value is 000.
in zp_menu, the two items have the same value 000 (as there is no other menu item before).

**Comment by sbillard** [comment]
The 'sort_order' field should never be empty. Try doing a sort on your pages tab. change the order then change it back. If that does not fail it should fix the issue.

**Comment by vincent3569** [comment]
ok, I reorder pages and now there is a sort order and the page appears when I use menu item "all zenpage page".

**Comment by vincent3569** [comment]
so the root cause of this false issue remains:
when I create a new page, there is no `sort_order` value stored in database.
I have to manually sort the page to add a value for `sort_order`

**Comment by acrylian** [comment]
I am on it already. This issue also applies to adding all categories.

> when I create a new page, there is no sort_order value stored in database.
> I have to manually sort the page to add a value for sort_order

Yes, because the page does not "know" about the others then and has not been sorted yet. So a manual sort is what fixes it. 

The issue of not all items added appearing is also related to the sort_order missing. This results in several items having the same value and the return array has the sort_order as the array key. Since keys are unique the ones with the same are "left behind".

**Comment by acrylian** [comment]
There is a fix in the support build that works around the occasion of pages or categories having no order set. They may therefore be not sorted the exactly same way but they are all added and displayed.
