### ISSUE TITLE
1.4.8 issue with admin>album and are.you.sure script

### ISSUE THREAD

**Issue by vincent3569** [zenphoto/zenphoto#934]
hi
every time I go to admin>albums>album sub tab, are.you.sure script is triggered and apply button is green, even if I don't have made a change.

**Comment by acrylian** [comment]
Sorry, I cannot reproduce this.

**Comment by vincent3569** [comment]
I have done a new setup, and the issue has disappeared
strange...

**Comment by acrylian** [comment]
Ok, good, I close this then. Possibly you had an outdated file or one of these funny browser cache issues. The script cause some troube but that should have been fixed a while ago.

**Comment by vincent3569** [comment]
hi Malte
I have a realy strange behavior:
with my professionnal computer (FF ESR 24.0), I don't have the issue
but with my home computer (FF 38.0), I still have the issue

**Comment by MarkRH** [comment]
I have FF 38.0.5 and have not seen this issue. Sounds like a browser cache/cookie issue. I would clear your browser cache and remove any cookies associated with the site. I seem to remember something funky happening with my gallery once and clearing the cookie solved it.  Left over junk from an earlier version or something.

**Comment by acrylian** [comment]
Cache and cookie issues it might be. Especially cache happens often to me. I generally disable the browser cache when testing things therefore.

**Comment by gjr-osweb** [comment]
Could be browser autofill as well. The password form is hidden on this page so might not notice if your browser is autofilling user/pass fields automatically.  I had this issue with Chrome, thought I fixed it awhile ago via: https://github.com/zenphoto/zenphoto/pull/857

**Comment by vincent3569** [comment]
hi
I have not reopened the ticket but I still have the problem.
I think gjr is right to point autofill of FF
as it becomes very difficult to use all days, I wish a robust solution to be found.

**Comment by acrylian** [comment]
You actually did reopen the ticket ;-) I never seen this but that does not mean that someone doesn't … I leave this to @gjr-osweb

**Comment by vincent3569** [comment]
I have the issue on admin/albums, admin/pages, admin/options/gallery.
each time, there is password form.
I think gjr point the right direction.

if it can help, I found this on the net:
https://developer.mozilla.org/en-US/docs/Web/Security/Securing_your_site/Turning_off_form_autocompletion

**Comment by acrylian** [comment]
I close this for now as I cannot reproduce anything further.
